### ISSUE TITLE
Most elegant way to use this within a laravel 5.6 project?

### ISSUE THREAD

**Issue by bluec** [mohd-isa/carbon#11]
Just wondering what would be the "best practice" way to use this within a Laravel 5.6 project?

To get started I have added master branch (since 1.0.0 release is currently out of date) to the project `package.json` as follows:

```
    "dependencies": {
        "carbon-admin": "mohd-isa/carbon#master"
    }
```

I then ran `npm install` and this installs the package and dependencies into node_modules. 

All good so far. Now, what is the best way to be able to build and then publish the assets within my project?

I feel we should be able to utilise laravel-mix here but I'm a bit new to this and trying to piece it all together....

One possible way seems that I can use `mix.copyDirectory` to copy the `dist/css` and `dist/js` etc directories from `node_modules/carbon-admin` into `public/css` and `public/js` etc. This would be a good start, but it seems I am then missing out on the opportunity to be able to adjust and rebuild the compiled assets using scss.

So, is there some laravel-mix recipe I can use so that I can use and rebuild the scss sources, or I am better just to use the precompiled assets that ship with this package and use copyDirectory as above to publish them? Or is there some other way?

Thanks for any guidance!

**Comment by bluec** [comment]
Ok, here's how I've got this working. Feedback welcome as this is new to me.

In Laravel project add carbon-admin and fontawesome-free to `package.json`:

```
    "dependencies": {
        "@fortawesome/fontawesome-free": "^5.2.0",
        "carbon-admin": "mohd-isa/carbon#master"
    }
```

Then run `npm install` to install these packages and their dependencies into node_modules directory.

In Laravel project `resources/assets/js/app.js` require the various JS libs:

```
try {
    window.$ = window.jQuery = require('jquery');
    require('popper.js');
    require('bootstrap');
    require('chart.js');
} catch (e) {}
```

In Laravel project `resources/assets/css/app.scss` import the various SCSS files:

```
// Variables
@import "_variables";

// Bootstrap
@import '~bootstrap/scss/bootstrap';

// Carbon
@import "~carbon-admin/src/sass/carbon/mixins";
@import "~carbon-admin/src/sass/carbon/layout";
@import "~carbon-admin/src/sass/carbon/sidebar";
@import "~carbon-admin/src/sass/carbon/header";
@import "~carbon-admin/src/sass/carbon/card";
@import "~carbon-admin/src/sass/carbon/alert";
@import "~carbon-admin/src/sass/carbon/buttons";
@import "~carbon-admin/src/sass/carbon/forms";
@import "~carbon-admin/src/sass/carbon/nav";
@import "~carbon-admin/src/sass/carbon/navbar";
@import "~carbon-admin/src/sass/carbon/utilities";
@import "~carbon-admin/src/sass/carbon/avatars";
@import "~carbon-admin/src/sass/carbon/switches";
@import "~carbon-admin/src/sass/carbon/reboot";
@import '~carbon-admin/src/sass/styles';
```

Copy `node_modules/carbon-admin/src/sass/carbon/_variables.scss` to `resources/assets/sass/_variables.scss` - you can edit this file to override some of the default variables used by bootstrap and carbon.

Now to compile and deploy the JS and SCSS resources we use `webpack.mix.js` in our Laravel project:

```
mix.js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css')
    .copyDirectory('node_modules/simple-line-icons/css', 'public/vendor/simple-line-icons/css')
    .copyDirectory('node_modules/simple-line-icons/fonts', 'public/vendor/simple-line-icons/fonts')
    .copyDirectory('node_modules/@fortawesome/fontawesome-free/css', 'public/vendor/fontawesome/css')
    .copyDirectory('node_modules/@fortawesome/fontawesome-free/js', 'public/vendor/fontawesome/js')
    .copyDirectory('node_modules/@fortawesome/fontawesome-free/sprites', 'public/vendor/fontawesome/sprites')
    .copyDirectory('node_modules/@fortawesome/fontawesome-free/svgs', 'public/vendor/fontawesome/svgs')
    .copyDirectory('node_modules/@fortawesome/fontawesome-free/webfonts', 'public/vendor/fontawesome/webfonts')
;
```

And that's pretty much it.

Theoretically, if you now run `npm run dev` it should create `public/js/app.js` and `public/css/app.css` which will include all the JS libraries and compiled CSS respectively.

**Comment by bluec** [comment]
> However you don't need to copy the fonts into your public directory as webpack already does that for you.

Does it? I initially didn't have those copyDirectory() commands and the fonts weren't published. How does webpack know to publish them and how does it know where to publish them to?

**Comment by mohd-isa** [comment]
Yes it does.

Check this doc
https://laravel.com/docs/5.6/mix#url-processing

**Comment by bluec** [comment]
Wow this is cool. I am learning a lot here. To make this work though I obviously have to import the font-awesome and simple-line-icons within the app.scss. So this makes the entire `resources/assets/css/app.scss` look like this:

```

// Fonts
@import url("https://fonts.googleapis.com/css?family=Raleway:300,400,600");

// Variables
@import "_variables";

// Font Awesome
@import '~@fortawesome/fontawesome-free/scss/fontawesome';
@import '~@fortawesome/fontawesome-free/scss/regular';
@import '~@fortawesome/fontawesome-free/scss/solid';
@import '~@fortawesome/fontawesome-free/scss/brands';

// Simple Line Icons
@import '~simple-line-icons/scss/simple-line-icons';

// Bootstrap
@import '~bootstrap/scss/bootstrap';

// Carbon
@import "~carbon-admin/src/sass/carbon/mixins";
@import "~carbon-admin/src/sass/carbon/layout";
@import "~carbon-admin/src/sass/carbon/sidebar";
@import "~carbon-admin/src/sass/carbon/header";
@import "~carbon-admin/src/sass/carbon/card";
@import "~carbon-admin/src/sass/carbon/alert";
@import "~carbon-admin/src/sass/carbon/buttons";
@import "~carbon-admin/src/sass/carbon/forms";
@import "~carbon-admin/src/sass/carbon/nav";
@import "~carbon-admin/src/sass/carbon/navbar";
@import "~carbon-admin/src/sass/carbon/utilities";
@import "~carbon-admin/src/sass/carbon/avatars";
@import "~carbon-admin/src/sass/carbon/switches";
@import "~carbon-admin/src/sass/carbon/reboot";
```

**Comment by mohd-isa** [comment]
yea exactly
