### ISSUE TITLE
Scrollbar issue

### ISSUE THREAD

**Issue by chriskonnertz** [mohd-isa/carbon#2]
Hello,

when I navigate to the Chart.js example page http://carbon.smartisan.io/chartjs.html with Opera 50.0 on Windows and the inner window size is 1961px width and 1153px height the vertical scrollbar at the right side of the window will appear and disappear in an endless loop. It's kinda flickering.

This screenshot shows the state when the scrollbar is visible: http://abload.de/img/scrollbar_bug87utx.jpg

It's a little hard to describe.  Unfortunately I could not make a video.

When I use Firefox 47.0.2 the bug occurs as well.

**Comment by mohd-isa** [comment]
Hi

I couldn't re-produce the issue. What is your screen resolution?

Also, can you try adding this styling and check if it remains?

```
html {
 overflow-y: scroll !important;
}
```

**Comment by chriskonnertz** [comment]
I added `overflow-y: scroll !important;` via inline CSS to the `html` Element and yes, that worked.

> What is your screen resolution?
3440px w x 1440 px h (UWQHD)

But I believe only the inner browser window solution matters.

**Comment by mohd-isa** [comment]
Yes, you are right. I've managed to reproduce it. Thanks!

**Comment by mohd-isa** [comment]
The previous solution works but it will always display a scrollbar and it's undesirable. So I will look for another solution. Any suggestion is highly appreciated.

**Comment by mohd-isa** [comment]
After doing some searches I found it's chart.js issue.

Please refer to this issue for more details https://github.com/chartjs/Chart.js/issues/4179

**Comment by sergegl** [comment]
> After doing some searches I found it's chart.js issue.
> 
> Please refer to this issue for more details [chartjs/Chart.js#4179](https://github.com/chartjs/Chart.js/issues/4179)

I noticed if you set width: fit-content; to a parent content the issue is fixed.
  .chartjs-size-monitor {
    width: fit-content;
  }

Give it a shot.
