### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by Francismori7** [mohd-isa/carbon#3]
Hello guys, very nice work. I love it.

Just wondering if this will be readily available from NPM packages? That way we don't stay at mercy of code updates going unnoticed.

**Comment by mohd-isa** [comment]
Thanks for the feedback

I will add this soon.

**Comment by mohd-isa** [comment]
npm package is available now. 

Refer to the [documentation](https://github.com/mohd-isa/carbon/wiki/Installation) for more details.
